apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-fish-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fish
  template:
    metadata:
      labels:
        app: fish
    spec:
      containers:
        - name: gofish
          image: darkxlayers/go-fish
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
